project:
  type: website

website:
  title: "CS 5805 Blog Posts"
  navbar:
    right:
      - text: Blog
        href: blog.qmd 

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

